name: Ollama Infinite Tunnel with NPort

on:
  workflow_dispatch:  # рдореИрдиреНрдпреБрдЕрд▓ рдЯреНрд░рд┐рдЧрд░
  schedule:
    - cron: '0 */6 * * *'  # рд╣рд░ 6 рдШрдВрдЯреЗ рдореЗрдВ рд╕реНрд╡рддрдГ рдкреБрдирдГрдЪрд╛рд▓реВ

jobs:
  ollama-tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # GitHub рдХрд╛ рдЕрдзрд┐рдХрддрдо рд╕рдордп (6 рдШрдВрдЯреЗ)

    steps:
    - name: Ollama рд╕реНрдерд╛рдкрд┐рдд рдХрд░реЗрдВ
      run: |
        sudo curl -fsSL https://ollama.com/install.sh | sh
        sudo ollama serve >/dev/null 2>&1 &
        sleep 15

    - name: рдиреЗрдЯрд╡рд░реНрдХ рд╕реБрд░рдХреНрд╖рд╛ рдЕрдХреНрд╖рдо рдХрд░реЗрдВ
      run: |
        sudo ufw disable
        sudo iptables -F
        sudo sysctl -w net.ipv4.ip_forward=1

    - name: NPort рдЯрдирд▓ рд╕реЗрдЯрдЕрдк
      run: |
        sudo apt install nodejs
        npm install -g localtunnel 
        curl https://loca.lt/mytunnelpassword
        lt --port 8000 --local_host 127.0.0.1
        npx nport -s mainsjsj -p 11434 > nport.log 2>&1 &
        sleep 20
        echo "PUBLIC_URL=$(grep 'Public URL' nport.log | awk '{print $NF}')" >> $GITHUB_ENV

    - name: рд╕рддрдд рдЪрд▓рдиреЗ рд╡рд╛рд▓рд╛ рд▓реВрдк
      run: |
        while true; do
          echo "ЁЯФД рд╕рд░реНрд╡рд░ рд╕рдХреНрд░рд┐рдп | $(date)"
          echo "ЁЯМР рд╕рд╛рд░реНрд╡рдЬрдирд┐рдХ рдкрд╣реБрдБрдЪ URL: ${{ env.PUBLIC_URL }}"
          echo "ЁЯФУ рд╕рднреА рдкреЛрд░реНрдЯреНрд╕ рдЦреБрд▓реЗ рд╣реИрдВ (11434/80)"
          curl -s localhost:11434 || echo "тЭМ Ollama рд╕рд░реНрд╡рд░ рддреНрд░реБрдЯрд┐"
          sleep 300
        done

    - name: рдЯрдирд▓ рдЬрд╛рдирдХрд╛рд░реА рдкреНрд░рджрд░реНрд╢рд┐рдд рдХрд░реЗрдВ
      run: |
        echo "тЬЕ рд╕рдлрд▓рддрд╛: Ollama рд╕рд░реНрд╡рд░ рд╕рдХреНрд░рд┐рдп!"
        echo "ЁЯФЧ NPort рдЯрдирд▓ URL: ${{ env.PUBLIC_URL }}"
        echo "тЪая╕П рдЪреЗрддрд╛рд╡рдиреА: рд╕рднреА рд╕реБрд░рдХреНрд╖рд╛ рдирд┐рдпрдо рдирд┐рд╖реНрдХреНрд░рд┐рдп рдХрд░ рджрд┐рдП рдЧрдП рд╣реИрдВ"
