name: Persistent NPort Tunnel Setup

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build and Run Docker Container
        run: |
          docker build -t myapp .
          docker run -d -p 5000:5000 --name myapp_container myapp
          sleep 10  # Wait for the app to start

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y openssh-client jq

      - name: Generate Random Subdomain
        run: |
          SUBDOMAIN=$(openssl rand -hex 4)  # Generates a random 8-character hex string
          echo "SUBDOMAIN=$SUBDOMAIN" >> $GITHUB_ENV  # Store it for later use

      - name: Start NPort Tunnel
        run: |
          echo "Starting NPort Tunnel with subdomain: $SUBDOMAIN"

          # Start the tunnel using npx (without global install)
          npx nport -s $SUBDOMAIN -p 5000 > nport_output.txt 2>&1 &

          sleep 15  # Allow tunnel to initialize

          # Extract the actual tunnel URL (ignore any unrelated output)
          TUNNEL_URL=$(grep -o 'https://[^ ]*' nport_output.txt | head -n 1)

          if [[ -z "$TUNNEL_URL" ]]; then
            echo "Error: Could not fetch valid NPort Tunnel URL!"
            exit 1
          fi

          echo "Generated Tunnel URL: $TUNNEL_URL"

          # Save tunnel URL to instance.json
          echo "{ \"tunnel_url\": \"$TUNNEL_URL\" }" > instance.json

      - name: Commit and Push Tunnel URL
        run: |
          git diff --quiet && echo "No changes to commit" || (
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add instance.json
            git commit -m "Updated tunnel URL"
            git push
          )
