name: Run OLLAMA Server with Auto Restart

on:
  workflow_dispatch:  # मैन्युअल स्टार्ट के लिए
  schedule:
    - cron: "*/350 * * * *"  # हर 350 मिनट बाद ऑटोमैटिक स्टार्ट

jobs:
  run-ollama-server:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # GitHub का मैक्सिमम टाइमआउट
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OLLAMA
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "OLLAMA installed successfully!"

      - name: Start OLLAMA Server
        run: |
          nohup ollama serve > ollama.log 2>&1 &
          sleep 5  # सर्वर स्टार्ट होने का इंतजार करें
          echo "OLLAMA Server started!"

      - name: Install Pinggy
        run: |
          curl -fsSL https://github.com/pinggy-io/pinggy/releases/latest/download/pinggy-linux-amd64 -o pinggy
          chmod +x pinggy
          echo "Pinggy installed successfully!"

      - name: Start Tunnel and Restart Every 55 Minutes
        run: |
          while true; do
            echo "Starting new Pinggy tunnel..."
            ./pinggy http 127.0.0.1:11434 --region us > tunnel.log 2>&1 &
            sleep 10  # टनल शुरू होने का इंतजार करें
            TUNNEL_URL=$(grep -oE 'https://[a-zA-Z0-9.-]+' tunnel.log | head -1)
            echo "Tunnel is live at: $TUNNEL_URL"
            echo "Tunnel URL: $TUNNEL_URL" >> $GITHUB_ENV  # URL को स्टोर करें
            
            echo "Waiting for 55 minutes before restarting tunnel..."
            sleep 3300  # 55 मिनट (55 * 60)
            
            echo "Restarting tunnel..."
            pkill -f pinggy  # पुराने टनल को बंद करें
          done
