name: Run Ollama with Loophole

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  run-ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y wget curl

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "Ollama installed successfully!"

      - name: Kill Any Existing Ollama Process
        run: |
          if pgrep -x "ollama" > /dev/null; then
            echo "Ollama is already running. Stopping it..."
            sudo pkill -9 ollama || true  # Force kill if needed, ignore errors
            sleep 5
          fi

      - name: Start Ollama
        run: |
          echo "Starting Ollama..."
          nohup ollama serve > ollama.log 2>&1 &  # Run Ollama in the background
          sleep 10

      - name: Pull DeepSeek Model
        run: |
          echo "Downloading deepseek-r1:1.5b model..."
          ollama run deepseek-r1:1.5b &

      - name: Start Loophole
        run: |
          echo "Downloading Loophole..."
          curl -L --output loophole https://raw.githubusercontent.com/NitinBot001/deepseek_r1-1.5b_api/main/loophole
          
          echo "Checking file details..."
          ls -lah loophole  # Ensure file exists
          file loophole  # Verify file type
          cat loophole | head -n 10  # Inspect contents

          echo "Setting permissions..."
          chmod +x loophole || { echo "Failed to set permissions"; exit 1; }
          
          echo "Moving loophole to /usr/local/bin..."
          sudo mv loophole /usr/local/bin/ || { echo "Failed to move loophole to /usr/local/bin"; exit 1; }
          
          echo "Verifying loophole is in PATH..."
          which loophole || { echo "Loophole not found in PATH"; exit 1; }

          echo "Running Loophole..."
          sudo /usr/local/bin/loophole account login &
          sudo /usr/local/bin/loophole http 11434 &

          echo "Waiting for tunnel URL..."
          sleep 30  # Ensure loophole has time to start

          ps aux | grep loophole  # Debugging: Check if loophole is running

      - name: Keep Alive
        run: |
          echo "Keeping workflow alive for 5 hours 45 minutes..."
          sleep 20700
