name: Run OLLAMA Server with Auto Restart

on:
  workflow_dispatch:  # मैन्युअल स्टार्ट के लिए
  schedule:
    - cron: "*/350 * * * *"  # हर 350 मिनट बाद ऑटोमैटिक स्टार्ट

jobs:
  run-ollama-server:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # GitHub का मैक्सिमम टाइमआउट
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OLLAMA
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "OLLAMA installed successfully!"

      - name: Start OLLAMA Server
        run: |
          nohup ollama serve > ollama.log 2>&1 &
          sleep 5  # सर्वर स्टार्ट होने का इंतजार करें
          echo "OLLAMA Server started!"

      - name: Start Tunnel and Restart Every 55 Minutes
        run: |
          while true; do
            echo "Starting new Pinggy tunnel using SSH..."
            nohup ssh -p 443 -L4300:localhost:4300 -o StrictHostKeyChecking=no \
                -o ServerAliveInterval=30 -t -R0:localhost:5000 ap.a.pinggy.io x:https > pinggy_output.txt 2>&1 &
            
            sleep 15  # टनल स्टार्ट होने का इंतजार करें
            
            # Extract tunnel URL, ignoring "dashboard.pinggy.io"
            TUNNEL_URL=$(grep -o 'https://[^ ]*' pinggy_output.txt | grep -v 'dashboard.pinggy.io' | head -n 1)

            if [[ -z "$TUNNEL_URL" ]]; then
              echo "Error: Tunnel URL not found!"
              cat pinggy_output.txt  # Debugging के लिए पूरा लॉग दिखाएं
              exit 1
            fi

            echo "Tunnel is live at: $TUNNEL_URL"
            echo "Tunnel URL: $TUNNEL_URL" >> $GITHUB_ENV  # URL को स्टोर करें
            
            echo "Waiting for 55 minutes before restarting tunnel..."
            sleep 3300  # 55 मिनट (55 * 60)
            
            echo "Restarting tunnel..."
            pkill -f "ssh -p 443"  # पुराने टनल को बंद करें
          done
