name: Run OLLAMA Server with Auto Restart

on:
  workflow_dispatch:  # मैन्युअल स्टार्ट के लिए
  schedule:
    - cron: "*/350 * * * *"  # हर 350 मिनट बाद ऑटोमैटिक स्टार्ट

jobs:
  run-ollama-server:
    runs-on: ubuntu-latest
    timeout-minutes: 350  # GitHub का मैक्सिमम टाइमआउट
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OLLAMA
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "OLLAMA installed successfully!"

      - name: Start OLLAMA Server
        run: |
          nohup ollama serve > ollama.log 2>&1 &
          sleep 5  # सर्वर स्टार्ट होने का इंतजार करें
          echo "OLLAMA Server started!"

      - name: Install Pinggy (Updated)
        run: |
          curl -o pinggy "https://s3.ap-south-1.amazonaws.com/public.pinggy.binaries/cli/v0.1.6/linux/amd64/pinggy"
          chmod +x pinggy
          echo "Pinggy installed successfully!"

      - name: Start Tunnel and Restart Every 55 Minutes
        run: |
          while true; do
            echo "Starting new Pinggy tunnel..."
            nohup ./pinggy -p 443 -L4300:localhost:4300 -R0:localhost:14344 a.pinggy.io > pinggy.log 2>&1 &
            sleep 5  # टनल स्टार्ट होने का इंतजार करें

            # Pinggy लॉग से टनल URL निकालें
            TUNNEL_URL=$(tail -f pinggy.log | grep -oE 'https://[a-zA-Z0-9.-]+' | head -1)
            
            if [[ -z "$TUNNEL_URL" ]]; then
              echo "Error: Tunnel URL not found!"
              cat pinggy.log  # Debugging के लिए लॉग दिखाएं
              exit 1
            fi

            echo "Tunnel is live at: $TUNNEL_URL"
            echo "Tunnel URL: $TUNNEL_URL" >> $GITHUB_ENV  # URL को स्टोर करें
            
            echo "Waiting for 55 minutes before restarting tunnel..."
            sleep 3300  # 55 मिनट (55 * 60)
            
            echo "Restarting tunnel..."
            pkill -f pinggy  # पुराने टनल को बंद करें
          done
