name: Run Ollama with LocalTunnel

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  run-ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install localtunnel
        run: npm install -g localtunnel

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "Ollama installed successfully!"

      - name: Kill Any Existing Ollama Process
        run: |
          if pgrep -x "ollama" > /dev/null; then
            echo "Ollama is already running. Stopping it..."
            sudo pkill -9 ollama || true  # Force kill if needed, ignore errors
            sleep 5
          fi

      - name: Start Ollama
        run: |
          echo "Starting Ollama..."
          # nohup ollama serve > ollama.log 2>&1 &  # Run Ollama in the background
          ollama serve &
          sleep 10

      - name: Pull DeepSeek Model
        run: |
          echo "Downloading deepseek-r1:1.5b model..."
          ollama run deepseek-r1:1.5b &

      - name: Start LocalTunnel
        run: |
          echo "Starting LocalTunnel..."
          sudo lt --port 11434 &
          curl https://loca.lt/mytunnelpassword
          
          echo "Waiting for tunnel URL..."
          sleep 10  # Ensure localtunnel has time to start

      - name: Keep Alive
        run: |
          curl https://loca.lt/mytunnelpassword
          echo "Keeping workflow alive for 5 hours 45 minutes..."
          sleep 20700
