name: Run Ollama with LocalTunnel

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  run-ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install localtunnel
        run: npm install -g localtunnel

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "Ollama installed successfully!"

      - name: Start Ollama
        run: |
          echo "Starting Ollama..."
          ollama serve &  # Run in background
          sleep 10  # Give it time to start

          echo "Checking if Ollama is running..."
          until curl -s http://localhost:11434/api/status | grep -q "running"; do
            sleep 5
          done
          echo "Ollama is running!"

      - name: Pull DeepSeek Model
        run: |
          echo "Downloading deepseek-r1:1.5b model..."
          curl -X POST http://localhost:11434/api/pull -d '{"name": "deepseek-r1:1.5b"}'

          echo "Waiting for model to download..."
          until curl -s http://localhost:11434/api/models | grep -q "deepseek-r1"; do
            sleep 10
          done
          echo "Model is ready!"

      - name: Start LocalTunnel
        run: |
          echo "Starting LocalTunnel..."
          lt --port 11434 > tunnel_output.txt 2>&1 &

          echo "Waiting for tunnel URL..."
          sleep 10  # Ensure localtunnel has time to start

          export TUNNEL_URL=$(grep -o 'https://[a-zA-Z0-9.-]*\.loca.lt' tunnel_output.txt)
          if [[ -z "$TUNNEL_URL" ]]; then
            echo "Failed to retrieve LocalTunnel URL" >&2
            exit 1
          fi

          echo "TUNNEL_URL=$TUNNEL_URL" >> $GITHUB_ENV
          echo "Ollama API is available at: $TUNNEL_URL"

      - name: Keep Alive
        run: |
          curl https://loca.lt/mytunnelpassword
          echo "Keeping workflow alive for 5 hours 45 minutes..."
          sleep 20700
