name: Run OLLAMA Server with Auto Restart

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Fixed cron: Every 6 hours

jobs:
  run-ollama-server:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OLLAMA
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "OLLAMA installed successfully!"

      - name: Stop Existing OLLAMA Servers
        run: |
          # Kill all running OLLAMA processes
          pkill -f "ollama serve" || true  # Ignore errors if no process exists
          sleep 2  # Allow time for termination

      - name: Start OLLAMA Server
        run: |
          nohup ollama serve --host 0.0.0.0 > ollama.log 2>&1 &  # Add --host 0.0.0.0
          sleep 5
          echo "OLLAMA Server started!"

      - name: Start Tunnel and Restart Every 55 Minutes
        run: |
          while true; do
            echo "Starting new Pinggy tunnel..."
            sudo apt install nodejs 
            sudo npx nport -s ollamazjdh -p 11434 
            echo "Waiting 55 minutes before restarting..."
            sleep 21300
            
          done
