name: Download and Store AI Model with Git LFS

on: 
  workflow_dispatch:

jobs:
  download-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Enable Git LFS

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Create model directory
        run: mkdir -p model

      - name: Download AI Model
        run: wget -O model/Llama-3.2-3B-Instruct-Q4_K_M.gguf "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf"

      - name: Track model file using Git LFS
        run: |
          git lfs track "model/Llama-3.2-3B-Instruct-Q4_K_M.gguf"
          git add .gitattributes

      - name: Commit and Push Model File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add model/Llama-3.2-3B-Instruct-Q4_K_M.gguf
          git commit -m "Added AI model using Git LFS"
          git push origin main
